"""ReportLab implementation of EngagementDeckRendererPort. Only file
allowed to import reportlab in this context. Lays out a full engagement as
a multi-section case deck: Situation (problem framing) / Evidence / Quant
Analysis / Recommendation — the actual shape of a case document, not a
JSON dump of the engagement's linked IDs. Sections that aren't linked yet
are simply omitted, so a partially-complete engagement still produces a
sensible (if shorter) deck rather than an error.
"""
from __future__ import annotations

import io
from datetime import datetime

from reportlab.graphics.charts.barcharts import HorizontalBarChart
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from sdie.workspace.application.dto import EngagementDeckData
from sdie.workspace.application.ports import EngagementDeckRendererPort
from sdie.workspace.domain.entities import Engagement

_INK = colors.HexColor("#0d1117")
_LEDGER = colors.HexColor("#1E6B62")
_MUTED = colors.HexColor("#5A6472")

_STATUS_LABELS = {
    "framing": "Framing",
    "evidence_gathering": "Evidence Gathering",
    "quant_analysis": "Quant Analysis",
    "synthesis": "Synthesis",
    "complete": "Complete",
}


class ReportLabEngagementDeckRenderer(EngagementDeckRendererPort):
    def render(self, engagement: Engagement, deck_data: EngagementDeckData) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            topMargin=0.7 * inch,
            bottomMargin=0.7 * inch,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
        )

        styles = self._styles()
        story: list = []

        story.extend(self._cover_section(engagement, styles))

        if deck_data.problem_framing:
            story.append(PageBreak())
            story.extend(self._situation_section(deck_data, styles))

        if deck_data.evidence_documents:
            story.append(PageBreak())
            story.extend(self._evidence_section(deck_data, styles))

        if deck_data.financial_model or deck_data.decision_analysis:
            story.append(PageBreak())
            story.extend(self._quant_section(deck_data, styles))

        if deck_data.synthesis:
            story.append(PageBreak())
            story.extend(self._synthesis_section(deck_data, styles))

        story.append(Spacer(1, 16))
        story.append(
            Paragraph(
                "Generated by the Strategic Decision Intelligence Engine. Each section reflects "
                "only what has actually been linked to this engagement — nothing here was inferred "
                "beyond the underlying analyses and cited evidence.",
                styles["Footer"],
            )
        )

        doc.build(story)
        return buffer.getvalue()

    # ------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------

    def _cover_section(self, engagement: Engagement, styles: dict) -> list:
        status_label = _STATUS_LABELS.get(engagement.status.value, engagement.status.value)
        return [
            Paragraph("STRATEGIC DECISION INTELLIGENCE ENGINE", styles["Eyebrow"]),
            Paragraph("Case Deck", styles["Eyebrow2"]),
            Spacer(1, 6),
            Paragraph(engagement.title, styles["Title"]),
            Spacer(1, 4),
            Paragraph(
                f"Generated {datetime.now().strftime('%B %d, %Y')} \u00b7 Status: {status_label}",
                styles["Meta"],
            ),
            Spacer(1, 20),
            Paragraph(
                "This deck compiles every stage of this engagement that has been completed so "
                "far, in the order a case team would present it: the problem as framed, the "
                "evidence gathered, the quantitative analysis performed, and the recommendation "
                "it produced.",
                styles["Body"],
            ),
        ]

    def _situation_section(self, deck_data: EngagementDeckData, styles: dict) -> list:
        pf = deck_data.problem_framing
        assert pf is not None
        elements: list = [
            Paragraph("01 \u2014 SITUATION", styles["SectionHeading"]),
            Paragraph(pf.title, styles["SubHeading"]),
            Paragraph(
                f"Framework: {pf.framework.replace('_', ' ').title()} \u00b7 "
                f"{pf.completion_ratio:.0%} of sections completed",
                styles["Meta"],
            ),
            Spacer(1, 10),
        ]
        for section_key, values in pf.entries.items():
            if not values:
                continue
            elements.append(Paragraph(section_key.replace("_", " ").title(), styles["Heading"]))
            for v in values:
                elements.append(Paragraph(f"\u2022 {v}", styles["Body"]))
            elements.append(Spacer(1, 6))
        return elements

    def _evidence_section(self, deck_data: EngagementDeckData, styles: dict) -> list:
        elements: list = [
            Paragraph("02 \u2014 EVIDENCE", styles["SectionHeading"]),
            Paragraph(
                f"{len(deck_data.evidence_documents)} source document(s) gathered for this "
                "engagement.",
                styles["Meta"],
            ),
            Spacer(1, 10),
        ]
        for d in deck_data.evidence_documents:
            elements.append(Paragraph(d.title, styles["Heading"]))
            elements.append(Paragraph(d.source_label, styles["SourceLabel"]))
            elements.append(Paragraph(f"\u201c{d.excerpt}\u201d", styles["Evidence"]))
            elements.append(Spacer(1, 8))
        return elements

    def _quant_section(self, deck_data: EngagementDeckData, styles: dict) -> list:
        elements: list = [Paragraph("03 \u2014 QUANT ANALYSIS", styles["SectionHeading"])]

        if deck_data.financial_model:
            fm = deck_data.financial_model
            elements.append(Paragraph(f"Financial model: {fm.project_name}", styles["SubHeading"]))
            rows = [["NPV", "IRR", "Payback"], [fm.npv, fm.irr_percent or "\u2014", fm.payback_period or "\u2014"]]
            table = Table(rows, colWidths=[1.8 * inch, 1.8 * inch, 1.8 * inch])
            table.setStyle(self._table_style())
            elements.append(table)
            if fm.flags:
                elements.append(Spacer(1, 6))
                for flag in fm.flags:
                    elements.append(Paragraph(f"\u26a0 {flag}", styles["Flag"]))
            elements.append(Spacer(1, 12))

        if deck_data.decision_analysis:
            da = deck_data.decision_analysis
            elements.append(Paragraph(f"Decision analysis: {da.title}", styles["SubHeading"]))
            elements.append(
                Paragraph(
                    f"Method: {da.method.replace('_', ' ')} \u00b7 Recommended: {da.recommended_option}",
                    styles["Meta"],
                )
            )
            elements.append(Spacer(1, 6))
            rankings = da.result_data.get("rankings")
            if rankings:
                chart = self._mcda_bar_chart(rankings)
                elements.append(chart)

        return elements

    def _synthesis_section(self, deck_data: EngagementDeckData, styles: dict) -> list:
        s = deck_data.synthesis
        assert s is not None
        elements: list = [
            Paragraph("04 \u2014 RECOMMENDATION", styles["SectionHeading"]),
            Paragraph(s.title, styles["SubHeading"]),
            Spacer(1, 8),
            Paragraph(s.current_recommendation, styles["Recommendation"]),
        ]
        if s.current_recommendation != s.recommended_option:
            elements.append(
                Paragraph(
                    f"Revised from the original quant-derived recommendation "
                    f"(\u201c{s.recommended_option}\u201d) across {s.override_count} recorded "
                    f"override(s).",
                    styles["Overridden"],
                )
            )
        elements.append(Spacer(1, 8))
        elements.append(Paragraph("Why", styles["Heading"]))
        elements.append(Paragraph(s.confidence_note, styles["Body"]))

        if s.evidence_citations:
            elements.append(Spacer(1, 8))
            elements.append(Paragraph("Cited evidence", styles["Heading"]))
            for c in s.evidence_citations:
                elements.append(
                    Paragraph(f'\u201c{c.excerpt}\u201d \u2014 <i>{c.source_label}</i>', styles["Evidence"])
                )

        return elements

    # ------------------------------------------------------------------
    # Shared helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _table_style() -> TableStyle:
        return TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _INK),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D0D0")),
            ]
        )

    @staticmethod
    def _mcda_bar_chart(rankings: list[dict]) -> Drawing:
        top = rankings[:5]
        labels = [r["option"][:22] for r in top]
        values = [r["weighted_score"] for r in top]

        drawing = Drawing(420, 30 + 22 * len(top))
        chart = HorizontalBarChart()
        chart.x, chart.y = 100, 10
        chart.width, chart.height = 280, 20 * len(top)
        chart.data = [values]
        chart.categoryAxis.categoryNames = labels
        chart.categoryAxis.labels.fontSize = 8
        chart.valueAxis.valueMin = 0
        chart.valueAxis.valueMax = 1
        chart.bars[0].fillColor = _LEDGER
        drawing.add(chart)
        return drawing

    @staticmethod
    def _styles() -> dict[str, ParagraphStyle]:
        base = getSampleStyleSheet()
        return {
            "Eyebrow": ParagraphStyle(
                "Eyebrow", parent=base["Normal"], textColor=_LEDGER, fontSize=9,
                fontName="Helvetica-Bold", spaceAfter=2,
            ),
            "Eyebrow2": ParagraphStyle(
                "Eyebrow2", parent=base["Normal"], textColor=_MUTED, fontSize=9,
            ),
            "Title": ParagraphStyle("Title", parent=base["Title"], textColor=_INK, fontSize=24, leading=28),
            "Meta": ParagraphStyle("Meta", parent=base["Normal"], textColor=_MUTED, fontSize=8),
            "SectionHeading": ParagraphStyle(
                "SectionHeading", parent=base["Normal"], textColor=_LEDGER, fontSize=13,
                fontName="Helvetica-Bold", spaceAfter=8,
            ),
            "SubHeading": ParagraphStyle(
                "SubHeading", parent=base["Normal"], textColor=_INK, fontSize=13,
                fontName="Helvetica-Bold", spaceAfter=4,
            ),
            "Heading": ParagraphStyle(
                "Heading", parent=base["Normal"], textColor=_LEDGER, fontSize=10,
                fontName="Helvetica-Bold", spaceBefore=6, spaceAfter=4,
            ),
            "Recommendation": ParagraphStyle(
                "Recommendation", parent=base["Normal"], textColor=_INK, fontSize=16,
                fontName="Helvetica-Bold", leading=20,
            ),
            "Overridden": ParagraphStyle(
                "Overridden", parent=base["Normal"], textColor=_MUTED, fontSize=8.5,
                fontName="Helvetica-Oblique", spaceBefore=4,
            ),
            "Body": ParagraphStyle("Body", parent=base["Normal"], textColor=_INK, fontSize=10, leading=14),
            "SourceLabel": ParagraphStyle(
                "SourceLabel", parent=base["Normal"], textColor=_LEDGER, fontSize=8.5, spaceAfter=2,
            ),
            "Evidence": ParagraphStyle(
                "Evidence", parent=base["Normal"], textColor=_INK, fontSize=9, leading=13,
                leftIndent=10, spaceAfter=4,
            ),
            "Flag": ParagraphStyle(
                "Flag", parent=base["Normal"], textColor=colors.HexColor("#8A6D1E"), fontSize=8.5,
                leading=12, spaceAfter=2,
            ),
            "Footer": ParagraphStyle(
                "Footer", parent=base["Normal"], textColor=_MUTED, fontSize=7.5, leading=10,
            ),
        }
